version: 2
updates:
  # Flutter / Pub dependencies
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
